app/categories/models.py
from datetime import datetime
from app.extensions.database import db, CRUDMixin

class Category(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80))
    category = db.Column(db.String(80))
    task = db.Column(db.String(250))
    tag = db.relationship('Tag', backref='category', uselist=False, lazy=True )

class Tag(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    tagName = db.Column(db.String(80))
    description = db.Column(db.String(80))
    updated_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    note_tags = db.relationship('NoteTag', backref='tag', lazy=True)


class NoteTag (db.Model, CRUDMixin):
    note_id = db.Column(db.Integer, db.ForeignKey('note.id'), primary_key=True)
    tag_id = db.Column(db.Integer, db.ForeignKey('tag.id'), primary_key=True)
    number_of_notes = db.Column(db.Integer)

app/notes/models.py
from app.extensions.database import db, CRUDMixin

class Note(db.Model, CRUDMixin):
    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(db.String(80), unique=True)
    title = db.Column(db.String(80))
    content = db.Column(db.String(250))
    note_tags = db.relationship('NoteTag', backref='note', lazy=True )

app/users/models.py
from app.extensions.database import db, CRUDMixin
from flask_login import UserMixin

class User(db.Model, CRUDMixin, UserMixin):
  id = db.Column(db.Integer, primary_key = True)
  email = db.Column(db.String(128), index = True, unique = True)
  password = db.Column(db.String(1024))

app/api/__init__.py
from . import routes

app/api/routes.py
from .services.serialize_categories import serialize_categories
from ..categories.models import Category
from flask import Blueprint, jsonify, request
from os import environ

blueprint = Blueprint('api', __name__)

@blueprint.get('/api/v1/categories')
def categories():
  if environ.get('API_KEY') == request.headers.get('X-API-KEY'):
    categories = Category.query.all()
    return jsonify (
        serialize_categories(categories)
    )
  else:
    return jsonify({'error': 'Invalid API key'}), 401

app/app.py
from . import notes, simple_pages, categories, api, users
from flask import Flask, redirect, url_for, render_template
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager

def create_app():
    app = Flask(__name__)
    #app.config.from_object('app.config')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['NOTES_PER_PAGE'] = 4

    register_blueprints(app)
    register_extensions(app)

    return app



# Blueprints
def register_blueprints(app:Flask):
    app.register_blueprint(notes.routes.blueprint)
    app.register_blueprint(simple_pages.routes.blueprint)
    app.register_blueprint(categories.routes.blueprint)
    app.register_blueprint(api.routes.blueprint)
    app.register_blueprint(users.routes.blueprint)

def register_extensions(app: Flask):
  db.init_app(app)
  migrate.init_app(app, db, compare_type=True)
  login_manager.init_app(app)

app/categories/__init__.py
from . import models, routes

app/categories/routes.py
from flask import Blueprint, render_template, request, current_app
from app.notes.models import Note
from app.categories.models import Category, Tag,  NoteTag
from .services.create_category import create_category
from flask_login import login_required

blueprint = Blueprint('categories', __name__)

@blueprint.get('/checkout')
@login_required
def get_checkout():
  notes = Note.query.all()

  return render_template('categories/category.html', notes = notes)

@blueprint.post('/checkout')
def post_checkout():
  #Add exceptions with try and except
  try:
    notes = Note.query.all()

    #validations
    if not all([
        request.form.get('name'),
        request.form.get('category'),
        request.form.get('task')

    ]):
        raise Exception('Please fill out all the fields')
    
    create_category(request.form, notes)
    return render_template('categories/category.html', notes = notes)
  except Exception as error_message:
     error = error_message or 'An error occured while processing your note. Please make sure to enter valid data'
     current_app.logger.info(f'Error creating an category: {error}')
     return render_template('categories/category.html', 
                            notes = notes,
                            error = error)

app/notes/__init__.py
from . import routes, models

app/notes/routes.py
from .models import Note
from flask import Blueprint, render_template, request, current_app

blueprint = Blueprint('notes', __name__)

# Notes route
@blueprint.route('/notes')
def notes():
    page_number = request.args.get('page', 1, type=int)
    notes_pagination = Note.query.paginate(page=page_number, per_page=current_app.config['NOTES_PER_PAGE'])
    return render_template('notes/notes.html', notes_pagination=notes_pagination)

@blueprint.route('/notes/<slug>')
def note(slug):
    # return slug
    note = Note.query.filter_by(slug=slug).first()
    #x = note_data[slug]
    return render_template('notes/tasks.html', note=note)

@blueprint.route('/run-seed')
def run_seed():
    if not Note.query.filter_by(slug='Groceries').first():
        import app.scripts.seed
        return 'Database seed completed!'
    else:
        return 'Nothing to run.'

app/simple_pages/__init__.py
from . import routes

app/simple_pages/routes.py
from flask import Blueprint, render_template

blueprint = Blueprint('simple_pages', __name__)
# Home route
@blueprint.route('/')
def index():
    return render_template('home.html')

# contact route
@blueprint.route('/contact')
def contact():
    return render_template('contact.html')

app/users/__init__.py
from . import routes, models

app/users/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.users.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user


blueprint = Blueprint('users', __name__)

@blueprint.get('/register')
def get_register():
  return render_template('users/register.html')

@blueprint.post('/register')
def post_register():
    #exception handling
    try:
        #validation
        if request.form.get('password') != request.form.get('password_confirmation'):
            raise Exception('The password confirmation must match the password.')
        elif User.query.filter_by(email=request.form.get('email')).first():
            raise Exception('The email address is already registered.')

        #encrypt password using user model
        user = User(
        email=request.form.get('email'),
        password=generate_password_hash(request.form.get('password'))
        )
        user.save()

        login_user(user)

        #redirect user to notes page after login
        return redirect(url_for('notes.notes'))
    except Exception as error_message:
        error = error_message or 'An error occurred while creating a user. Please make sure to enter valid data.'
        return render_template('users/register.html', error=error)


@blueprint.post('/login')
def post_login():
  try:
    user = User.query.filter_by(email=request.form.get('email')).first()

    if not user:
      raise Exception('No user with the given email address was found.')
    elif not check_password_hash(user.password, request.form.get('password')):
      raise Exception('The password does not appear to be correct.')
    
    login_user(user)
    
    return redirect(url_for('notes.notes'))
    
  except Exception as error_message:
    error = error_message or 'An error occurred while logging in. Please verify your email and password.'
    return render_template('users/login.html', error=error)


@blueprint.get('/logout')
def logout():

  logout_user()

  return redirect(url_for('users.get_login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%block head%}
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{%block title%}{%endblock%}</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {%endblock%}
</head>
<body>
    {%block body%}{%endblock%}    
</body>
<footer>
    <hr>
    {% if current_user.is_authenticated %}
      <small>
        Logged in as {{ current_user.email }}.
        <a href="{{ url_for('users.logout') }}">Logout</a>
      </small>
    {% endif %}
  </footer>
</html>

app/templates/categories/category.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{%block title%}Sticky{%endblock%}

{%block body%}
    <div class="contact-navbar">
        <ul>
            <li><a href="/">Go to Home</a></li>
        </ul>
    </div>
    <form method="POST">
        <h2 class="notes-heading">Write your note</h2>  
        {% if error %}
            <p style="color: tomato;">{{ error }}</p>
        {% endif %}
        <div>
            <label for="name">Task name</label>
            <input type="text" name="name" id="name" placeholder="What to buy tomorrow">
        </div>
        <div>
            <label for="category">Category of Task</label>
            <input type="text" name="category" id="category" placeholder="random">
        </div>
        <div>
            <label for="task">Task</label>
            <input type="text" name="task" id="task" placeholder="Lorem ipsum whatever">
        </div>
        <input type="submit" value="Submit Task">

    </form>   
{% endblock %}
</html>

app/templates/contact.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{%block title%}Sticky{%endblock%}

{%block body%}
    <div class="contact-main">
        <!-- Navbar -->
        <div class="contact-navbar">
            <ul>
                <li><a href="/">Home</a></li>
            </ul>
        </div>
        <!-- Image -->
        <div class="contact-img">
            <img src="https://images.unsplash.com/photo-1670272506154-080063eee4be?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxlZGl0b3JpYWwtZmVlZHwxfHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=1600&q=60" alt="Image of people laughing">
        </div>
        <!-- Contact Information -->
        <div class="contact-info">
            <h2 class="contact-heading">Contact Us</h2>
            <h3 class="contact-subtext">Have questions about how to use Sticky? <br> Send us an email using the form below.</h3>
            <p class="contact-paragragh">Lohmühlenstraße 65, <br> 12435 Berlin</p>
            <button class="contact-button"><a href="heizal.nagginda@code.berlin">Send us an email</a></button>
        </div>
    </div>  
{% endblock %}
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{%block title%}Sticky{%endblock%}

{%block body%}
    <div class="main-page">
        <!-- Navbar -->
        <div class="navbar">
            <ul>
                <li><a href="/contact">Contact us</a></li>
            </ul>
        </div>
        <!-- Hero content and words -->
        <div class="hero-text">
            <h1 class="main-heading">Sticky</h1>
            <h3 class="main-subtext">Note taking made easier</h3>
            <p class="main-paragraph">Focus on taking the notes, we'll take care of managing them! </p>
        </div>
        <!-- Link to notes page - dynamic page -->
        <div class="hero-button">
            <button class="main-button"><a href="/notes">Write something</a></button>
        </div>
    </div>  
{% endblock %}
</html>

app/templates/notes/notes.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{%block title%}Sticky{%endblock%}

{%block body%}
    <div class="contact-navbar">
        <ul>
            <li><a href="/">Go to Home</a></li>
        </ul>
    </div>
    <h1 class="notes-heading">My Sticky Notes</h1>
    <ul class="notes-list">
        {% for note in notes_pagination.items%}
        <li><input type="checkbox">
            <a href="notes/{{note.slug}}" class="notes-name">{{note.slug}}</a>
        </li>
        {%endfor%}
    </ul>
    <nav>
        {% if notes_pagination.prev_num %}
          <a href="{{ url_for('notes.notes', page=notes_pagination.prev_num) }}">Previous Page</a>
        {% else %}
          <span>Previous Page</span>
        {% endif %}
        <span> - </span>
        {% if notes_pagination.next_num %}
          <a href="{{ url_for('notes.notes', page=notes_pagination.next_num) }}">Next Page</a>
        {% else %}
          <span>Next Page</span>
        {% endif %}
      </nav>
{% endblock %}
</html>

app/templates/notes/tasks.html
<!DOCTYPE html>
<html lang="en">
{% extends 'base.html' %}

{%block title%}Sticky{%endblock%}

{%block body%}
    <div class="contact-navbar">
        <ul>
            <li><a href="/notes">See my tasks</a></li>
        </ul>
    </div>
    <ul class="notes-list">
        <li>
            <h2 class="notes-heading">{{note['title']}}</h2>
            <h3>{{note.content}}</h3>
            <h4>{{note.categoryName}}</h4>
        </li>
    </ul>
{% endblock %}
</html>

app/templates/users/login.html
{% extends 'base.html' %}

{% block title %}Sticky | Login{% endblock %}

{% block body %}
  <h1>Login</h1>

  {% if error %}
  <p style="color: tomato;">{{ error }}</p>
  {% endif %}

  <form method="POST">
    <div>
      <label for="email">Email</label>
      <input type="email" name="email" id="email" required>
    </div>

    <div>
      <label for="password">Password</label>
      <input type="password" name="password" id="password" required>
    </div>
    
    <input type="submit" value="Login">
  </form>  
{% endblock %}

app/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Sticky | Register{% endblock %}

{% block body %}
  <h1>Register</h1>

  {% if error %}
  <p style="color: tomato;">{{ error }}</p>
  {% endif %}

  <form method="POST">
    <div>
      <label for="email">Email</label>
      <input type="email" name="email" id="email" required>
    </div>

    <div>
      <label for="password">Password</label>
      <input type="password" name="password" id="password" required>
    </div>

    <div>
      <label for="password_confirmation">Password Confirmation</label>
      <input type="password" name="password_confirmation" id="password_confirmation" required>
    </div>
    
    <input type="submit" value="Sign Up">
  </form>  
{% endblock %}